# Generated by Django 3.1.7 on 2021-03-27 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hexafuel_oil_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinformation',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hexafuel_oil_app.user'),
        ),
    ]
