# Generated by Django 3.1.6 on 2021-04-01 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hexafuel_oil_app', '0002_clientinformation_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinformation',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hexafuel_oil_app.user'),
        ),
    ]
